version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb-container
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=mydb
      - MARIADB_USER=myuser
      - MARIADB_PASSWORD=mypassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin-container
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8081:80"
           
  api-gateway:
    build: ./api-gateway
    image: api-gateway-image
    container_name: api-gateway-container
    ports:
      - "9000:9000"

  eureka-server:
    build: ./eureka-server
    image: eureka-server-image
    container_name: eureka-server-container
    ports:
      - "8761:8761"

  order:
    build: ./order
    restart: always
    image: order-image
    container_name: order-container
    ports:
      - "9091:9091"
     
  article:
    build: ./article
    restart: always
    image: article-image
    container_name: article-container
    ports:
      - "9090:9090"
      
  shop:
    build: ./shop
    restart: always
    image: shop-image
    container_name: shop-container
    ports:
      - "8004:8004"
      
  customer:
    build: ./customer
    restart: always
    image: customer-image
    container_name: customer-container
    ports:
      - "8000:8000"
      
  zipkin-server:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
  
  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.0
    hostname: zookeeper
    container_name: zookeeper-container
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-server:
    image: confluentinc/cp-kafka:7.0.0
    hostname: kafka-server
    container_name: kafka-container
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:29092,PLAINTEXT_HOST://kafka-server:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
      KAFKA_JMX_PORT: 9991
      KAFKA_JMX_HOSTNAME: kafka-server
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"

      
volumes:
  mariadb_data:
    driver: local