version: '3'
services:
  mariadb:
    image: mariadb
    networks:
     - vas_repo_shop-network
    container_name: mariadb-container
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=mydb
      - MARIADB_USER=myuser
      - MARIADB_PASSWORD=mypassword
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    networks:
     - vas_repo_shop-network
    container_name: phpmyadmin-container
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8081:80"
           
  api-gateway:
    build: ./api-gateway
    image: api-gateway-image
    networks:
     - vas_repo_shop-network
    container_name: api-gateway-container
    ports:
      - "9000:9000"

  eureka-server:
    build: ./eureka-server
    image: eureka-server-image
    networks:
     - vas_repo_shop-network
    container_name: eureka-server-container
    ports:
      - "8761:8761"

#  order:
#    build: ./order
#    restart: always
#    image: order-image
#    container_name: order-container
#   ports:
#      - "9091:9091"
     
  article:
    build: ./article
    restart: on-failure
    image: article-image
    networks:
     - vas_repo_shop-network
    container_name: article-container
    ports:
      - "9090:9090" 
    environment:
    - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    - SPRING_KAFKA_CONSUMER_GROUP_ID=shop_group
    depends_on:
    - kafka
      
  shop:
    build: ./shop
    restart: on-failure
    image: shop-image
    networks:
     - vas_repo_shop-network
    container_name: shop-container
    ports:
      - "8004:8004"
    environment:
    - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    - SPRING_KAFKA_CONSUMER_GROUP_ID=shop_group
    depends_on:
    - kafka
    
 
  customer:
    build: ./customer
    restart: always
    image: customer-image
    networks:
     - vas_repo_shop-network
    container_name: customer-container
    ports:
      - "8000:8000"
    environment:
    - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    - SPRING_KAFKA_CONSUMER_GROUP_ID=shop_group
    depends_on:
    - kafka
      
  zipkin-server:
    image: openzipkin/zipkin
    networks:
     - vas_repo_shop-network
    ports:
      - "9411:9411"
      
  zookeeper:
    image: wurstmeister/zookeeper
    networks:
     - vas_repo_shop-network
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    networks:
     - vas_repo_shop-network
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CONSUMER_GROUP: shop_group
    
      
volumes:
  mariadb_data:
    driver: local

networks:
  vas_repo_shop-network:
    external: true